apiVersion: v1
kind: Service
metadata:
  name: fixme-review
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: fixme-review
  ports:
  - name: review
    port: 4007
    targetPort: 4007
    protocol: TCP
