apiVersion: v1
kind: Service
metadata:
  name: fixme-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: fixme-mysql
  ports:
  - name: fixme-mysql
    port: 3306
    targetPort: 3306
