@baseUrl = http://localhost:4000
@urlPath = /api/gateway/v1/

###
# Seed database
# Route: GET /auth/seed/:count
PUT {{baseUrl}}{{urlPath}}/auth/seed/10
Accept: application/json

###
# Seed database
# Route: GET /auth/seed/:count
PUT {{baseUrl}}{{urlPath}}/seller/seed/10
Accept: application/json